/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE Nishant Parmar
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int i=0;

void  Delay()
{
for(i=0;i<100000;i++);
}

int main(void) {

	uint32_t *clkreg = (uint32_t*) 0x4002102C;
	uint32_t *Modreg = (uint32_t *) 0x50000400;
	uint32_t *outreg = (uint32_t *) 0x50000414;
	*clkreg |= 0x00000002;

	//clear the bit
	*Modreg &= 0xFFFFF4FF;

	//Set The bit
	*Modreg |= 0x00000400;

	while(1)
	{
	//OUTPUT
	*outreg |= 0x00000020;
	Delay();     //1Sec
	*outreg &= 0xFFFFFF0F;
	Delay();
	}
}
